version: 0.1.1.{build}
environment:
  CI: true
nuget:
  account_feed: true
  project_feed: true
  disable_publish_on_pr: true
build_script:
- cmd: >-
    npm install -g npm

    npm --version

    node --version

    npm run build-ci
